spring:
  profiles:
    active:
      - dev
  application:
    name: lldforge_backend

  # PostgreSQL database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/lld-forge-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  #  data:
  #    redis:
  #      host: ${SPRING_REDIS_HOST}
  #      port: ${SPRING_REDIS_PORT}
  #      password: ${SPRING_REDIS_PASSWORD}
  #      timeout: 60000
  #      lettuce:
  #        pool:
  #          max-active: 8
  #          max-idle: 8
  #          min-idle: 0
  #
  #  cache:
  #    type: redis

  # Mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ankushpaulclg2002@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

lldforge:
  adminEmail: ankushpaulclg2002@gmail.com
server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /api

app:
  mentor-lock:
    wait-time: 10 # in seconds
    lease-time: 30 # in seconds

# Jwt configuration
  jwt:
    secret: +5Y35EA91Ec1zS64aT3ZvJWeYsgEQpVTeFr7TQmRIA8=
    expiration: 3600000
    refresh-expiration: 864000000


# Razorpay sdk configuration
razorpay:
  api:
    key: ${RAZORPAY_API_KEY}
    secret: ${RAZORPAY_SECRET}