
spring:
  profiles:
    active:
      - dev
  application:
    name: lldforge_backend

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${ClientId}
            client-secret: ${ClientSecrets}
            scope:
              - read:user
              - user:email

  datasource:
    url: jdbc:mysql://localhost:3306/lldforge
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false

#  data:
#    redis:
#      host: ${SPRING_REDIS_HOST}
#      port: ${SPRING_REDIS_PORT}
#      password: ${SPRING_REDIS_PASSWORD}
#      timeout: 60000
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#
#  cache:
#    type: redis

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

lldforge:
  adminEmail: ${adminEmail}
server:
  port: 8081

app:
  mentor-lock:
    wait-time: 10 # in seconds
    lease-time: 30 # in seconds
